### PR TITLE
Simple Atari 800XL Memory Map

### PR DESCRIPTION
**Pull request by zbyti**

### CODE REVIEW

**Comment by zbyti** [comment]
Of course if we want to use memory up to $bfff we have to define our own Display List and set LMS.

**Comment by zbyti** [comment]
If segment_default_end=$BFFF then 
```
HIMEM ($2E5) = $bc1f
```
$bc1f contains DL 

```
BC1F: 00 70 70 70 42 40 BC 02 02 02 02 02 02 02 02 02  ♥pppB@<┃┃┃┃┃┃┃┃┃
BC2F: 02 02 02 02 02 02 02 02 02 02 02 02 02 02 41 20  ┃┃┃┃┃┃┃┃┃┃┃┃┃┃A 
BC3F: BC 
```
LMS = $bc40

then bc40 + $3c0 (960 bytes for gr.0) = $c000


everything is correct with this setup.

**Comment by zbyti** [comment]
I'm waiting for this PR to be merged and write more examples for a8

**Comment by KarolS** [comment]
Looks good, thanks!
Sorry for taking my time, I've been busy recently.

**Pull request merged**
