### PR TITLE
refactor and MPT player examble

### PR DESCRIPTION
**Pull request by zbyti**
Will be one or two more examples ;)

### CODE REVIEW

**Comment by zbyti** [comment]
OK. Ready to merge :]

**Comment by KarolS** [comment]
Could you add credits for the player binaries and for the CMC music?

**Comment by zbyti** [comment]
OK. I try to find the author.

**Comment by zbyti** [comment]
Now it's good to go ;)

**Comment by zbyti** [comment]
```
Freude, schöner Götterfunken,
     Tochter aus Elisium,
Wir betreten feuertrunken
     Himmlische, dein Heiligthum.
Deine Zauber binden wieder,
     was der Mode Schwerd getheilt;
Bettler werden Fürstenbrüder,
     wo dein sanfter Flügel weilt.
```
ping :]

**Comment by KarolS** [comment]
Sorry. Life and stuff.

**Comment by zbyti** [comment]
Great to hear You are alive ;)

**Comment by KarolS** [comment]
Last few weeks were quite busy for me, I think I'll have more free time from now on.

**Pull request merged**
