### PR TITLE
Improved #36: Added compile flags for enabling tests

### PR DESCRIPTION
**Pull request by agg23**
Furthers the work I started in #36, enabling switching between testing and building without tests with a single flag (no file modifications required).

Standard building:
```
sbt compile
sbt assembly
```

Building with tests:
```
sbt -DincludeTests compile
sbt -DincludeTests assembly
```

@KarolS, make sure to try this out with tests before merging. I still haven't set up a testing environment, so I may have messed something up.

### CODE REVIEW

**Comment by KarolS** [comment]
The funny thing is that I was pretty sure that this would work.

It doesn't. `if`s don't work like that in SBT. Nothing works like expected in SBT. SBT turns out to be a giant jumbled pile of three-layered mess: https://www.lihaoyi.com/post/SowhatswrongwithSBT.html

I managed to get the dependencies to be conditional (see https://stackoverflow.com/questions/30337672/conditional-libraries-in-build-sbt), but I haven't figured out how to disable tests conditionally. I tried applying https://stackoverflow.com/questions/42915843/redefine-an-sbt-task-conditional-on-a-setting but it didn't work.

**Comment by agg23** [comment]
Hm... What does it end up doing wrong?

**Comment by agg23** [comment]
I realized that you can run `sbt "inspect libraryDependencies"`, which I would think properly represents the libraries that are included:

```
[info] Setting: scala.collection.Seq[sbt.librarymanagement.ModuleID] = List(org.scala-lang:scala-library:2.12.11,
com.lihaoyi:fastparse:1.0.0, org.apache.commons:commons-configuration2:2.2, org.eclipse.lsp4j:org.eclipse.lsp4j:0.9.0,
net.liftweb:lift-json:3.4.2, org.scalatest:scalatest:3.0.8:test, com.codingrodent.microprocessor:Z80Processor:2.0.2:test)
```

With the `-DincludeTests=true` flag:
```
[info] Setting: scala.collection.Seq[sbt.librarymanagement.ModuleID] = List(org.scala-lang:scala-library:2.12.11,
com.lihaoyi:fastparse:1.0.0, org.apache.commons:commons-configuration2:2.2, org.eclipse.lsp4j:org.eclipse.lsp4j:0.9.0,
net.liftweb:lift-json:3.4.2, org.scalatest:scalatest:3.0.8:test, com.codingrodent.microprocessor:Z80Processor:2.0.2:test,
org.graalvm.js:js-scriptengine:20.2.0:test)
```

Besides the fact that I accidentally included some test dependencies in the non-`includeTests` section, what is breaking here?

**Comment by agg23** [comment]
Here, how does this look @KarolS?

No tests:
```
[info] Setting: scala.collection.Seq[sbt.ModuleID] = List(org.scala-lang:scala-library:2.12.11, com.lihaoyi:fastparse:1.0.0,
org.apache.commons:commons-configuration2:2.2, org.scalatest:scalatest:3.0.8:test)
```

`-DincludeTests=true`:
```
[info] Setting: scala.collection.Seq[sbt.ModuleID] = List(org.scala-lang:scala-library:2.12.11, com.lihaoyi:fastparse:1.0.0,
org.apache.commons:commons-configuration2:2.2, org.scalatest:scalatest:3.0.8:test,
com.codingrodent.microprocessor:Z80Processor:2.0.2:test, NeatMonster:Intel8086:1.0:test,
com.loomcom.symon:symon:1.3.0-SNAPSHOT:test, com.grapeshot:halfnes:061:test,
eu.rekawek.coffeegb:coffee-gb:1.0.0:test, roug.org.osnine:osnine-core:2.0-SNAPSHOT:test,
org.graalvm.sdk:graal-sdk:20.2.0:test, org.graalvm.js:js:20.2.0:test, org.graalvm.js:js-scriptengine:20.2.0:test)
```

**Comment by KarolS** [comment]
I tested it and it seems to work. Thanks!

**Comment by KarolS** [comment]
I did one change to make tests enabled by default, as this is what most build systems use (and having `sbt test` do nothing is at least weird).

**Comment by agg23** [comment]
> I did one change to make tests enabled by default, as this is what most build systems use (and having sbt test do nothing is at least weird).

Agreed. I was going to make this change myself. I just got all of the tests running locally, and realized my mistake.

**Pull request merged**
