### PR TITLE
initial atari_lynx support

### PR DESCRIPTION
**Pull request by Nullious**
tested with 
millfork -t atari_lynx examples\atari_lynx\atari_lynx_demo.mfk -o lynx
and loaded into handy emulator
coloured bars and a large logo that can be moved and scaled

### CODE REVIEW

**Comment by KarolS** [comment]
This looks fine. I'll merge it and tweak few minor things later today.

Few questions:

* shouldn't the `atari_lynx_hardware` module import the `joy` module, as it's using implicitly?

* when implementing the `joy` interface, you seem to have chosen to store all buttons into `input_btn`, when the `nes_joy` module uses separate variables for each button. Since I'm open to making some incompatible changes, which of those two approaches do you think would be better when developing cross-platform games? I'm now thinking a bit about it and your approach could be more flexible than mine and I don't think we should worry about the number of buttons, as no platform should have more than 8.

* in the `atari_lynx_demo.mfk`, why are you doing `if input_dy==$ff` etc. instead of just adding/subtracting? `input_dx` and `input_dy` are signed, they should work with word-sized positions just fine

**Comment by Nullious** [comment]
1) yes that's true. it should be implicit 
2) the nes method is better I agree
3) also a good point. this was cobbled from my own testing which wasn't just xpos + joydir

**Comment by KarolS** [comment]
Drawbacks of the `nes_joy` method:
* it uses more RAM
* it makes it harded to parameterize buttons (you can't just have a button mask as a parameter somewhere)
* it requires using something else than `reset_joy` to zero the button state if there is more than one button

Drawbacks of the `atari_lynx_hardware` method:
* uses more ROM to test the buttons on 6502
* uses also a bit more ROM if there can ever be only one joypad

It's all a matter of tradeoffs.

Any preferences? I usually use Millfork for C64, and it has only one joystick button, so it doesn't matter to me.

**Comment by KarolS** [comment]
I merged it, did some tweaks and found a small bug in the compiler in the process.

Thanks again!

**Comment by Nullious** [comment]
Great thanks , didn't know there was a volatile keyword ;) I'll clean up SMS soon thanks for the cleanup/tips

**Pull request merged**
